In [2]:
#importing Numpy Library
import numpy as np

# 4.Program to Create array and print elements

In [3]:
array=np.array([11,12,13,14]) #created array
print(array)

[11 12 13 14]


In [4]:
array = np.array([[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]])
print(array)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


#5.Program to Create array and print its Shape

In [5]:
array = np.array([[11, 12, 13, 14], [15, 16, 17, 18]]) #created array

print(array.shape)

(2, 4)


#2.Program to print reverse elements of array

In [7]:
array= np.array([11, 12, 13, 14, 15, 16, 17]) #created array

print(array[::-1])

[17 16 15 14 13 12 11]


#1.Program to Create an array and resize it

In [10]:
array=np.arange(1,100,2).reshape(10,5)
print(array)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


#3.Program to Sort array in ascending order 

In [11]:
array = np.array([1, 31, 16, 4, 7, 55, 21, 14, 5])

print(np.sort(array)) 

[ 1  4  5  7 14 16 21 31 55]
